parser: "@typescript-eslint/parser"
parserOptions:
  project: "tsconfig.json"
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
env:
  node: true
  jest: true
rules:
  "@typescript-eslint/interface-name-prefix": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-explicit-any": 0
